[package]
name = "hello-world"
version = "0.0.0"
edition = "2018"
description = "wasm-pack sample"
license = "MIT / Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
