name: CI

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master", "ci" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Build-on-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodule
      run: git submodule update --init --recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run fmt
      run: cargo fmt

  Build-on-macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodule
      run: git submodule update --init --recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  Build-on-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodule
      run: git submodule update --init --recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  
