name: CI

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master", "ci" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
        rust: [nightly, beta, stable, 1.48.0]
        include:
          - compiler: gcc-7
            os: ubuntu-20.04
          - compiler: clang-7
            os: ubuntu-20.04            

    runs-on: ${{ matrix.os }}

    steps:
      - if: matrix.compiler == 'gcc-7'
        name: Install gcc
        run: |
          sudo apt-get update
          sudo apt-get install gcc-7 g++-7
          gcc --version
          g++ --version
      - if: matrix.compiler == 'clang-7'
        name: Install clang
        run: |
          sudo apt-get update
          sudo apt-get install clang-7
          clang --version
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - uses: actions/checkout@v3
      - name: Checkout submodule
        run: git submodule update --init --recursive
      - run: cargo build --verbose
      - run: cargo test --verbose

  fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodule
        run: git submodule update --init --recursive
      - run: cargo fmt